### ISSUE TITLE
The code for HGA in Multi-choice and Open-ended questions are different

### ISSUE THREAD

**Issue by LemonQC** [doc-doc/NExT-QA#10]
Why the two encoder is different? The first is in MC, the second is OE.
![image](https://user-images.githubusercontent.com/30914380/159860220-5f1ab412-f6a0-430e-81a0-3ab16d382192.png)
![image](https://user-images.githubusercontent.com/30914380/159860394-310d71e8-bad7-4224-98b9-695bf8905d23.png)

**Comment by doc-doc** [comment]
Hi, I recommend you to use the MC implemetation which is up-to-date. I am not quite remember the difference. It could be resulted from that I was doing some investigations on C3D(4096d) and I3D (2048d).  But It should be fine for both implementation.

**Comment by LemonQC** [comment]
> 

Ok, Thanks.

**Comment by HU-xiaobai** [comment]
@LemonQC  hello,  could I ask what does the up-to-date "MC implementation" mean? I am going to research the open-end answer.
