### ISSUE TITLE
test-open-ended dataset

### ISSUE THREAD

**Issue by yjyaoj** [doc-doc/NExT-QA#12]
We can not find the test-open-ended dataset for NExT-QA.

Can you give us some URL to download this part annotations?

Thank

**Comment by doc-doc** [comment]
Thanks for your interest. Test data for open-ended QA can be found in [NExT-OE](https://github.com/doc-doc/NExT-OE) readme. I also provide the [link](https://drive.google.com/file/d/1bXBFN61PaTSHTnJqz3R79mpIgEQPFGIU/view) here for convenience. The test videos are the same with NExT-QA. So, you can find the link provided in the readme of this repo.

**Comment by yjyaoj** [comment]
THANK
