### ISSUE TITLE
The number of Video is not matched to the descriptions

### ISSUE THREAD

**Issue by wonjiny** [doc-doc/NExT-QA#16]
According to this page([https://doc-doc.github.io/docs/nextqa.html]), the number of videos are the following.
Train: 3870, Val: 570, Test:1000, Total:5440

However, when I download the videos at here([https://xdshang.github.io/docs/vidor.html]), and test video==MissingVideo([https://drive.google.com/file/d/12WCsaOOlDQNaXILSxvL-hIM3TxV15dV3/view]), but the number of videos are not matched.

What do I miss?

**Comment by wonjiny** [comment]
I've got an reply from the author, Xiao Junbin. All videos are provided in the two links, https://xdshang.github.io/docs/vidor.html 
https://drive.google.com/file/d/12WCsaOOlDQNaXILSxvL-hIM3TxV15dV3/view 

And the number of videos can be checked with the provided map file, 
https://github.com/doc-doc/NExT-QA/tree/main/dataset/nextqa/

**Comment by PKUCSS** [comment]
@doc-doc Hello, Thanks for your great work and patient response. The link to the missing videos is invalid now ((https://drive.google.com/file/d/12WCsaOOlDQNaXILSxvL-hIM3TxV15dV3/view)), could you please update it?

**Comment by doc-doc** [comment]
Hi, thanks for the interest. I have updated the link in the data preparation section and all of the videos are now available via this [link](https://drive.google.com/file/d/1jTcRCrVHS66ckOUfWRb-rXdzJ52XAWQH/view)
