### ISSUE TITLE
Where is region_feat_n

### ISSUE THREAD

**Issue by PolarisHsu** [doc-doc/NExT-QA#17]
Dear Junbin,
Hi! About a year ago, the dataset seemed to consist of frame_feat, mot_feat, qas_feat and region_feat_n. Now I can't find the folder region_feat_n in Google Driver, and found that the files app_feat_xxx and mot_feat_xxx have been merged into app_mot_xxx, is there some change? How can I get region_feat_n? Thanks!

**Comment by doc-doc** [comment]
Hi, thanks for your interest.  The feature has been removed as it takes large amount of my online storage. Yes, I have merged the feature, which means that the first half of the tensor (0:2048) belongs to the appearance representation and the rest belongs to the motion (2048:4096).   The region feature can be found in HQGA (https://github.com/doc-doc/HQGA). The features is slightly different but should not affact the reults too much..
