### ISSUE TITLE
How to get appearance  feature for video representation with a shape as (16, 2048)

### ISSUE THREAD

**Issue by wangbq18** [doc-doc/NExT-QA#2]
Hi, I just find the data shape of appearance and motion feature for video representation whitch your provide in the vid_feat.zip is (16, 2048), but With code provided by [HCRN], the appearance  feature for video representation with a shape as (8, 16, 2048), So How can I get a  appearance  feature with shape as (16, 2048). Looking farword to your reply, thanks!

**Comment by doc-doc** [comment]
Please use the middle frame of the clip for appearance representation.

**Comment by wangbq18** [comment]
> Please use the middle frame of the clip for appearance representation.

Get it, thanks!

**Comment by zongzhao23** [comment]
Hi, thank you for sharing such a great codebase! Does "the middle frame of the clip" indicate that you use the 8th and 9th frame in each clip(16 frames total) for appearance representation? When concatenate the frame features, do you follow the original order of the 8 clips (e.g. [frames in the first clip: frames in the second clip: ... frames in the last clip]) ? Looking farword to your reply!

**Comment by doc-doc** [comment]
Hi, there is no need to be so precise, we actually chose the 9th (16//2, from 0) one .
Yes, the order should be kept same..

**Comment by zongzhao23** [comment]
Thanks for your reply! It may make sense for me. You chose one frame for each clip, so you set the clip number as 16 rather than 8 as the HCRN?

**Comment by HU-xiaobai** [comment]
@FFFFF123456 @wangbq18 hello, could I ask if you could abstract the same appearance feature that the author provided? For example, for the validation set, I set the clip as 16 and I abstract the 8th or 9th(actually I compare all the frames in one clip) frame appearance vector of the first clip and compare the first frame vector of the provide appearance vector, both dimension are (2048,), but I find the appearance vector is different. how about yours?

**Comment by wangbq18** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好!我已收到您的邮件！
