### ISSUE TITLE
Can I get the raw videos in the test set?

### ISSUE THREAD

**Issue by zjwbr** [doc-doc/NExT-QA#21]
Hi~It is really a good job, but I only found the feature file in this project. 
I want to extract features from the given video with my code. So, could you please provide the raw video in the test set? 
Thank you very much!

**Comment by doc-doc** [comment]
Hi, thanks for the interest. The link for the raw videos is given in the readme..

**Comment by zjwbr** [comment]
> Hi, thanks for the interest. The link for the raw videos is given in the readme..

But I can not find corresponding links of raw videos in ReadMe.md 
In this link, https://drive.google.com/file/d/1_MEqDeQHc8Y8Uw7eW58HVuZy2iyThILQ/view, I can only find feature files and annotations

**Comment by doc-doc** [comment]
Hi, it was highlighted in the data preparation section.

**Comment by zjwbr** [comment]
> Hi, it was highlighted in the data preparation section.

wow~~~~~~~~
I got it!
Thank you !
