### ISSUE TITLE
Cannot download from drive links

### ISSUE THREAD

**Issue by kahnchana** [doc-doc/NExT-QA#25]
Can an alternate download link be created to access the dataset? Current google drive links are not working. 

<img width="577" alt="image" src="https://github.com/doc-doc/NExT-QA/assets/17735127/c7ec040e-92ed-4036-9edd-75d85889b2a2">

**Comment by doc-doc** [comment]
Hi, can you please specify which link? Or you can try [this](https://drive.google.com/drive/folders/1gKRR2es8-gRTyP25CvrrVtV6aN5UxttF?usp=sharing) for all resources.

**Comment by kahnchana** [comment]
Okay, those links were broken yesterday. They are now working - sorry about any trouble. I am able to download.
