### ISSUE TITLE
How can I get the raw video data for the test set ?

### ISSUE THREAD

**Issue by Fly2flies** [doc-doc/NExT-QA#5]
Thank you for such a good work. 
I want to test the object features, but I'm missing some test video. How can I get the video data of the test set? 
[VidOR ](https://xdshang.github.io/docs/vidor.html) website seems to provide only train and val set.

**Comment by Fly2flies** [comment]
What’s more, I found that tran.csv also contains the video of the original test set, such as 3755261383

**Comment by doc-doc** [comment]
Hi, please find the missing videos [here](https://drive.google.com/file/d/12WCsaOOlDQNaXILSxvL-hIM3TxV15dV3/view?usp=sharing)

**Comment by zhangxi1997** [comment]
Thank you for the missing videos. I want to utilize the annotations in VidOR dataset. How can I get the annotations of these missing videos, especially for the annotations of the missing videos in train.csv?

**Comment by doc-doc** [comment]
Thanks for the interest, I will release them next week and let you know.

**Comment by doc-doc** [comment]
Hi, please find the relation annotations for the missing videos [here](https://drive.google.com/file/d/1RW8ck39n-yScGrOZWJ7gBr1jH3Iy4SSl/view?usp=sharing)
