### ISSUE TITLE
Does the videos have a caption？

### ISSUE THREAD

**Issue by LemonQC** [doc-doc/NExT-QA#8]
Can you provide a caption csv file for the video?

**Comment by doc-doc** [comment]
Do you mean caption annotation of the videos? There is no such annotations as we challenge visual reasoning in VideoQA.

**Comment by LemonQC** [comment]
Ok, thanks for your reply.


| |
Shandong University
|
|
***@***.***
|
On 3/17/2022 19:33，Junbin ***@***.***> wrote：

Do you mean caption annotation of the videos? There is no such annotations as we challenge visual reasoning in VideoQA.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
